apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: vieriu
    provider: github
    repository: jx3-azure-akv
    gitops.jenkins-x.io/pipeline: 'namespaces'
  name: vieriu-jx3-azure-akv
  namespace: jx
spec:
  httpCloneURL: https://github.com/vieriu/jx3-azure-akv.git
  org: vieriu
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jx3-azure-akv
  scheduler:
    kind: ""
    name: in-repo
  url: https://github.com/vieriu/jx3-azure-akv
