# Source: chartmuseum/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-x-chartmuseum
  labels:
    app: chartmuseum
    chart: chartmuseum-2.14.2
    heritage: "Helm"
    release: "chartmuseum"
  annotations:
    meta.helm.sh/release-name: 'chartmuseum'
  namespace: jx
type: Opaque
data:
  BASIC_AUTH_PASS: ZHVtbXk=
  BASIC_AUTH_USER: ZHVtbXk=
