# Source: jxboot-helmfile-resources/templates/jx-basic-auth-user-password-secret.yaml
apiVersion: v1
data:
  password: ""
  username: ""
kind: Secret
metadata:
  name: jx-basic-auth-user-password
  annotations:
    meta.helm.sh/release-name: 'jxboot-helmfile-resources'
  namespace: jx
type: Opaque
