# Source: lighthouse/templates/hmacsecret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: lighthouse-hmac-token
  labels:
    app: lighthouse-lighthouse
    chart: "lighthouse-1.1.52"
    release: "lighthouse"
    heritage: "Helm"
  annotations:
    meta.helm.sh/release-name: 'lighthouse'
  namespace: jx
type: Opaque
data:
  hmac: "dG9kbw=="
