# Source: nexus/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nexus
  labels:
    app: nexus-nexus
    chart: "nexus-0.1.41"
    release: "nexus"
    heritage: "Helm"
  annotations:
    meta.helm.sh/release-name: 'nexus'
  namespace: jx
type: Opaque
data:
  password: "dG9kbw=="
